### ISSUE TITLE
Any commits planned?

### ISSUE THREAD

**Issue by yckart** [zirhut/MooTools-BezierMove#1]
Would really like to see what you've done so far :)

**Comment by zirhut** [comment]
Sorry, but I do not have any plan to develop in MooTools anymore. There are libraries for jQuery already:
http://heygrady.com/blog/2011/07/20/animating-with-curves-in-jquery/
jquery.path - example: http://jqbezier.ericlesch.com/

**Comment by yckart** [comment]
You're totally right, reinventing the wheel is mostly not needed... I just had the dream, to drag along bezier curves (quadratic or cubic, doesn't matter). Both libraries you've linked are for tweening/animating, and I've no clue how to abstract those to follow along some [x,y] coordinates.

Of course, there is https://github.com/Mottie/Pathslider/ from Rob... However, it's a bit buggy and has not seen any updates for a long time...

But, I've to accept. Thanks for the fast reply :)
